name: GitHub Metrics - Achievements

on:
  workflow_dispatch:

jobs:
  achievements-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: moxer-mmh/metrics@master
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Azlouk-Ahmed
          base: ""
          plugin_achievements: yes
          plugin_achievements_secrets: no
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
